### ISSUE TITLE
How were the coordinates obtained and normalized?

### ISSUE THREAD

**Issue by danielcasanova12** [VoltyShock/Rust-NoRecoil#4]
Hello,

First of all, thank you for making this amazing software available!

I am trying to better understand how the coordinates were obtained and normalized in the code. Could you please provide more details on the process used to determine the exact coordinates used in the script?

Specifically, I am interested in knowing:
1. How did you obtain the exact coordinates for different actions (e.g., player posture, bullet count, weapon switching)?
2. What method was used to normalize these coordinates?
3. If there are specific tools or techniques that you recommend for this process, could you share them?

Thank you in advance for your help and attention!

**Comment by VoltyShock** [comment]
I cant lie, I made this 3 years ago during secondary school, I didn't do any real math or anything I did just bodge it together and it worked within the context that i used it. The amount of bullets never mattered because the recoil pattern reset after not firing for a few seconds in game. I just went in game and tested the values as the guns had very little randomized recoil, i didnt need something that was perfect just wanted something that would make it so i didnt have to invest shit tonnes of time to have a chance in game.
